### ISSUE TITLE
gcm_sender_id error

### ISSUE THREAD

**Issue by Otokiru** [realtime-framework/WebPushNotifications#1]
Changed gcm sender id to mine, and now it keeps having this alert error:

> Messaging: Please change your web app manifest's 'gcm_sender_id' value to '103953800507' to use Firebase messaging. (messaging/incorrect-gcm-sender-id).

**Comment by realtime-framework** [comment]
Have you also changed the Firebase initialisation code in the index.html file and entered your Firebase sender id in the service-worker.js file? It seems you are still using our demo configuration.

**Comment by Otokiru** [comment]
Yes i did

**Comment by Otokiru** [comment]
However, it still works when i manually grab and send the curl command. Just that the button to send the push on the page is disabled due to the error above.

**Comment by realtime-framework** [comment]
Maybe you need to unregister the service worker so it loads with the new changed config

**Comment by realtime-framework** [comment]
Our bad: according to Firebase documentation you need to enter that hard-code value in your manifest file. There's no need to enter your own sender id in the manifest as wrongly the README was stating.
